server.servlet.context-path=/mostrador
server.port=9000
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/mostrador
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}