server.servlet.context-path=/estante
server.port=9000
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/estante
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
